### ISSUE TITLE
A question about /vehicle_cmd

### ISSUE THREAD

**Issue by atinfinity** [tier4/aichallenge_bringup#5]
I used [twist_gate](https://gitlab.com/autowarefoundation/autoware.ai/core_planning/-/tree/1.13.0/twist_gate) to publish `/vehicle_cmd`.   
And, I checked `/vehicle_cmd` generated by twist_gate using `rostopic echo`.

```
header: 
  seq: 626
  stamp: 
    secs: 1585034558
    nsecs: 623529510
  frame_id: ''
steer_cmd: 
  header: 
    seq: 0
    stamp: 
      secs: 0
      nsecs:         0
    frame_id: ''
  steer: 0
accel_cmd: 
  header: 
    seq: 0
    stamp: 
      secs: 0
      nsecs:         0
    frame_id: ''
  accel: 0
brake_cmd: 
  header: 
    seq: 0
    stamp: 
      secs: 0
      nsecs:         0
    frame_id: ''
  brake: 0
lamp_cmd: 
  header: 
    seq: 0
    stamp: 
      secs: 0
      nsecs:         0
    frame_id: ''
  l: 0
  r: 0
gear: 0
mode: 0
twist_cmd: 
  header: 
    seq: 0
    stamp: 
      secs: 0
      nsecs:         0
    frame_id: ''
  twist: 
    linear: 
      x: 5.55555555556
      y: 0.0
      z: 0.0
    angular: 
      x: 0.0
      y: 0.0
      z: -0.0726724823873
ctrl_cmd: 
  linear_velocity: 5.55555555556
  linear_acceleration: 3.22997146803
  steering_angle: -0.0353041516245
emergency: 0
```

In this case, `gear` is set to 0. And, I could control the vehicle on LGSVL Simulator.  
But, there is the following description in [README.md](https://github.com/tier4/aichallenge_bringup/blob/master/README.md). Should `gear` be set to 64?

> 車両にはautoware_msgs/VehicleCmd型で制御コマンドを送ることができます。 本コンテストにおいてサポートしているコマンドはVehicleCmdの中のcontrol_cmd内部に存在するlinear_acceleration,steering_angleとなります。 また、gearの値は必ず64（ドライブ）に設定してください。
